spring:
  application:
    name: core-banking
  profiles:
    active: local
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: core
        jdbc:
          batch_size: 25
  flyway:
    enabled: true
    schemas: core
    default-schema: core

app:
  business-zone: Asia/Ho_Chi_Minh
  version: "@project.version@"

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
