spring:
  datasource:
    url: ${DATABASE_URL:${SPRING_DATASOURCE_URL}}
    username: ${DATABASE_USER:${SPRING_DATASOURCE_USERNAME}}
    password: ${DATABASE_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    show-sql: false
  flyway:
    enabled: true
