spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/core_banking}
    username: ${SPRING_DATASOURCE_USERNAME:mybi}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    show-sql: false
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
